basePath: /
definitions:
  controller._ResponseCommon:
    properties:
      code:
        description: 业务响应状态码
        type: integer
      data:
        description: 数据
        type: string
      message:
        description: 提示信息
        type: string
    type: object
  controller._ResponseLoginSuccess:
    properties:
      access_token:
        description: jwt access_token 验证使用
        type: string
      code:
        description: 业务响应状态码
        type: integer
      message:
        description: 提示信息
        type: string
      refresh_token:
        description: jwt refresh_token 刷新token
        type: string
      user_id:
        description: 登陆用户ID
        type: string
      username:
        description: 登陆用户昵称
        type: string
    type: object
  controller._ResponseRefreshToken:
    properties:
      access_token:
        description: jwt access_token 验证使用
        type: string
      code:
        description: 业务响应状态码
        type: integer
      message:
        description: 提示信息
        type: string
      refresh_token:
        description: jwt refresh_token 刷新token
        type: string
    type: object
  models.CategoryModel:
    properties:
      category_id:
        description: 社区ID
        example: "0"
        type: string
      category_name:
        description: 社区名称
        type: string
      created_time:
        $ref: '#/definitions/models.LocalTime'
        description: 社区创建时间
      id:
        description: ID
        type: integer
      introduction:
        description: 社区简介
        type: string
      updated_time:
        $ref: '#/definitions/models.LocalTime'
        description: 社区更新时间
    type: object
  models.CategoryRow:
    properties:
      id:
        description: 社区ID
        type: integer
      name:
        description: 社区名称
        type: string
    type: object
  models.LocalTime:
    properties:
      time.Time:
        type: string
    type: object
  models.ParamCategory:
    properties:
      category_name:
        description: 社区名称
        type: string
      introduction:
        description: 社区简介
        type: string
    required:
    - category_name
    - introduction
    type: object
  models.ParamLogin:
    properties:
      password:
        description: 密码
        example: "12456"
        type: string
      username:
        description: 用户名
        example: jack
        type: string
    required:
    - password
    - username
    type: object
  models.ParamPost:
    properties:
      author_id:
        description: 发帖作者
        type: integer
      category_id:
        description: 社区ID
        example: "0"
        type: string
      content:
        description: 帖子内容
        type: string
      post_id:
        description: 帖子ID
        type: integer
      status:
        description: 帖子状态
        type: integer
      title:
        description: 帖子标题
        type: string
    required:
    - category_id
    - content
    - title
    type: object
  models.ParamRefreshToken:
    properties:
      access_token:
        description: 令牌
        type: string
      refresh_token:
        description: 刷新令牌
        type: string
    required:
    - access_token
    - refresh_token
    type: object
  models.ParamSignUp:
    properties:
      password:
        description: 密码
        type: string
      re_password:
        description: 确认密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - re_password
    - username
    type: object
  models.ParamVote:
    properties:
      post_id:
        description: 投票的帖子id
        example: "0"
        type: string
      value:
        description: 投票结果， 1 赞成 0 取消 -1 反对
        example: "0"
        type: string
    required:
    - post_id
    - value
    type: object
  models.PostListDetail:
    properties:
      author_id:
        description: 帖子作者ID
        example: "0"
        type: string
      category_id:
        description: 社区ID
        example: "0"
        type: string
      category_name:
        description: 社区名称
        type: string
      content:
        description: 帖子内容
        type: string
      created_time:
        $ref: '#/definitions/models.LocalTime'
        description: 社区创建时间
      email:
        type: string
      gender:
        type: string
      id:
        description: ID
        type: integer
      introduction:
        description: 社区简介
        type: string
      password:
        type: string
      post_id:
        description: 帖子ID
        example: "0"
        type: string
      status:
        description: 帖子状态
        type: integer
      title:
        description: 帖子标题
        type: string
      updated_time:
        $ref: '#/definitions/models.LocalTime'
        description: 社区更新时间
      user_id:
        example: "0"
        type: string
      username:
        type: string
    type: object
  models.PostModel:
    properties:
      author_id:
        description: 帖子作者ID
        example: "0"
        type: string
      category_id:
        description: 帖子社区ID
        example: "0"
        type: string
      content:
        description: 帖子内容
        type: string
      created_time:
        $ref: '#/definitions/models.LocalTime'
        description: 帖子创建时间
      id:
        description: id
        type: integer
      post_id:
        description: 帖子ID
        example: "0"
        type: string
      status:
        description: 帖子状态
        type: integer
      title:
        description: 帖子标题
        type: string
      updated_time:
        $ref: '#/definitions/models.LocalTime'
        description: 帖子更新时间
    type: object
host: localhost:8080
info:
  contact: {}
  description: 使用gin开发简单帖子展示系统
  title: BlueBell Api
  version: "1.0"
paths:
  /categories:
    get:
      description: 社区列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CategoryRow'
      summary: 社区列表
      tags:
      - 社区
  /category:
    post:
      consumes:
      - application/json
      description: 新建社区
      parameters:
      - description: 社区
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/models.ParamCategory'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseCommon'
      summary: 新建社区
      tags:
      - 社区
  /category/{id}:
    get:
      description: 社区详情
      parameters:
      - default: "3730413906300928"
        description: 社区ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CategoryModel'
      summary: 社区详情
      tags:
      - 社区
  /category/{id}/posts:
    get:
      description: 获取某个社区下的所有帖子
      parameters:
      - default: "3730413906300928"
        description: 社区ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostModel'
      summary: 获取某个社区下的所有帖子
      tags:
      - 社区
  /login:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 登陆信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.ParamLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseLoginSuccess'
      summary: 登陆
      tags:
      - 用户
  /post:
    post:
      consumes:
      - application/json
      description: 存储帖子
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 帖子
        in: body
        name: posts
        required: true
        schema:
          $ref: '#/definitions/models.ParamPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseCommon'
      security:
      - ApiKeyAuth: []
      summary: 存储帖子
      tags:
      - 帖子
  /post/{id}:
    get:
      description: 帖子详情
      parameters:
      - default: "3765906580705280"
        description: 帖子ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostModel'
      summary: 帖子详情
      tags:
      - 帖子
  /post/vote:
    post:
      consumes:
      - application/json
      description: 用户可以给帖子投赞成或者反对票
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 投票
        in: body
        name: vote
        required: true
        schema:
          $ref: '#/definitions/models.ParamVote'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostListDetail'
      security:
      - ApiKeyAuth: []
      summary: 帖子投票
      tags:
      - 帖子
  /posts:
    get:
      description: 帖子列表
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: 每页大小
        in: query
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostListDetail'
      summary: 帖子列表
      tags:
      - 帖子
  /refresh:
    post:
      consumes:
      - application/json
      description: 刷新access_token
      parameters:
      - description: jwt验证信息
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/models.ParamRefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseRefreshToken'
      summary: 刷新token
      tags:
      - token
  /signup:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 注册信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.ParamSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseCommon'
      summary: 注册
      tags:
      - 用户
  /v2/posts:
    get:
      description: 可以根据发帖时间和帖子分数来获取帖子列表
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: 每页大小
        in: query
        name: size
        required: true
        type: integer
      - default: time
        description: 排序依据, time 时间 score 得分
        in: query
        name: order
        required: true
        type: string
      - default: asc
        description: 升序还是降序 asc 升序 desc 降序
        in: query
        name: sorts
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostListDetail'
      summary: 帖子列表
      tags:
      - 帖子
swagger: "2.0"
